# Generated by Django 2.2.4 on 2019-09-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('txt', models.TextField()),
            ],
            options={
                'ordering': ['pubDate'],
            },
        ),
    ]
