# Generated by Django 2.2.6 on 2019-10-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pubDate']},
        ),
    ]
