# Generated by Django 2.2.6 on 2020-01-15 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mass',
            name='priest',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, unique_for_date='day'),
        ),
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Data:')),
                ('startHour', models.TimeField(verbose_name='Godzina')),
                ('endHour', models.TimeField(verbose_name='Godzina')),
                ('priest', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, unique_for_date='day')),
            ],
        ),
    ]
