# Generated by Django 2.2.4 on 2019-09-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0002_auto_20190917_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mass',
            name='startTime',
            field=models.CharField(choices=[(2, '12:00'), (0, '6:00'), (1, '9:00'), (3, '18:00')], default=0, help_text='Godzina', max_length=10),
        ),
    ]
