# Generated by Django 2.2.6 on 2020-01-16 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mass', '0004_auto_20200116_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mass',
            name='priest',
        ),
        migrations.AddField(
            model_name='mass',
            name='priest',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, unique_for_date='day', verbose_name='Kapłan'),
        ),
    ]
