# Generated by Django 2.2.4 on 2019-09-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0005_auto_20190917_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mass',
            name='startTime',
            field=models.CharField(choices=[('18:00', '18:00'), ('12:00', '12:00'), ('6:00', '6:00'), ('9:00', '9:00')], default=0, help_text='Godzina', max_length=50, unique_for_date='day'),
        ),
    ]
