# Generated by Django 2.2.4 on 2019-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0007_auto_20190917_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mass',
            options={'ordering': ['day', 'startTime']},
        ),
        migrations.AlterField(
            model_name='mass',
            name='approved',
            field=models.CharField(max_length=50, verbose_name='Rodo txt'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='day',
            field=models.DateField(verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='intention',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Intencja:'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='startTime',
            field=models.CharField(choices=[('06:00', '06:00'), ('09:00', '09:00'), ('12:00', '12:00'), ('18:00', '18:00')], default=0, max_length=50, unique_for_date='day', verbose_name='Godzina:'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Imię i Nazwisko:'),
        ),
    ]
