# Generated by Django 2.2.6 on 2020-02-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mass', '0007_auto_20200116_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confession',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='confession',
            name='priest',
        ),
        migrations.AddField(
            model_name='confession',
            name='priest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique_for_date='day'),
        ),
    ]
