# Generated by Django 2.2.6 on 2019-10-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0008_auto_20190930_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mass',
            name='approved',
        ),
        migrations.AddField(
            model_name='mass',
            name='approve',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default='Nie', max_length=50, verbose_name='Akceptacja:'),
        ),
    ]
