# Generated by Django 2.2.6 on 2019-11-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0009_auto_20191018_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mass',
            name='approve',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default='Nie', max_length=50, null=True, verbose_name='Akceptacja:'),
        ),
    ]
