# Generated by Django 2.2.6 on 2020-02-11 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0010_auto_20200211_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='endHour',
            field=models.TimeField(verbose_name='Godzina Zakończenia'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='priest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kapłan'),
        ),
        migrations.AlterField(
            model_name='confession',
            name='startHour',
            field=models.TimeField(verbose_name='Godzina Rozpoczęcia'),
        ),
    ]
