# Generated by Django 2.2.6 on 2020-02-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass', '0011_auto_20200211_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confession',
            options={},
        ),
    ]
